theme: jekyll-theme-minima
title: Seda Bilaloglu
description: Welcome to my site! I am a data scientist/engineer and interested in Machine Learning applications in healthcare.

google_analytics: UA-138345422-1


