theme: jekyll-theme-dinky
title: Seda Bilaloglu
description: Welcome to my site! I am a data scientist/engineer and interested in Machine Learning applications in healthcare.

linkedin:
  zip_url: https://www.linkedin.com/in/seda-bilaloglu-013b9a2b/
  
google-scholar:
  zip_url: https://scholar.google.com/citations?user=7E1r-jQAAAAJ&hl=en
  
twitter:
  zip_url: https://twitter.com/sedabilaloglu

google_analytics: UA-138345422-1


